---
- name: "Role: common"
  hosts: all
  roles:
    - common
  tags:
    - common

- name: "Role: workstation"
  hosts: workstation
  roles:
    - workstation
  tags:
    - workstation

- name: "Role: solidus"
  hosts: solidus
  roles:
    - solidus
  tags:
    - solidus

- name: "Role: laptop"
  hosts: laptop
  roles:
    - laptop
  tags:
    - laptop
