---
- name: Install workstation tools
  become: yes
  apt:
    state: present
    name:
      - dex
      - fonts-hack
      - i3
      - smart-notifier
      - sshfs
      - build-essential
      - ansible
      - scrot

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - data
    - downloads

- name: Create .config/systemd/user directory
  file:
    path: ~/.config/systemd/user
    state: directory

- name: Deploy sshfs_auto unit file
  template:
    src: sshfs_auto.service.j2
    dest: .config/systemd/user/sshfs_auto.service

- name: Enable sshfs_auto unit
  systemd:
    daemon_reload: yes
    name: sshfs_auto
    enabled: yes
    scope: user
    state: started

- name: Copy ansible vault pass
  no_log: yes
  copy:
    src: /home/do/.vault_pass
    dest: /home/do/.vault_pass

- name: Ensure /etc/X11/xorg.conf.d exists
  become: yes
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: Copy xorg custom settings
  become: yes
  copy:
    src: 90-custom-xkb.conf
    dest: /etc/X11/xorg.conf.d/90-custom-xkb.conf

- name: Install rustup
  shell:
    warn: False
    cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
    creates: ~/.cargo/bin/rustup

- name: rustup update
  shell: ~/.cargo/bin/rustup update

- name: Download rust-analyzer
  shell:
    warn: False
    cmd: curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gzip -d > ~/bin/rust-analyzer; chmod +x ~/bin/rust-analyzer
