---
- name: Install sshfs
  become: yes
  apt:
    state: present
    name:
      - sshfs

- name: Create data directory
  file:
    path: ~/data
    state: directory

- name: Deploy sshfs_auto unit file
  template:
    src: sshfs_auto.service.j2
    dest: .config/systemd/user/sshfs_auto.service

- name: Enable sshfs_auto unit
  systemd:
    name: sshfs_auto
    enabled: yes
    scope: user
    state: restarted
    daemon_reload: yes
