---
- name: Install workstation tools
  become: yes
  apt:
    state: present
    name:
      - sshfs
      - smart-notify

- name: Create data directory
  file:
    path: ~/data
    state: directory

- name: Deploy sshfs_auto unit file
  template:
    src: sshfs_auto.service.j2
    dest: .config/systemd/user/sshfs_auto.service

- name: Enable sshfs_auto unit
  systemd:
    daemon_reload: yes
    name: sshfs_auto
    enabled: yes
    scope: user
    state: started

- name: Copy ansible vault pass
  no_log: yes
  copy:
    src: /home/do/.vault_pass
    dest: /home/do/.vault_pass
