---
- name: Deploy sources.list
  become: yes
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644 

- name: Upgrades
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Install useful tools
  become: yes
  apt:
    state: present
    name:
      - bash-completion
      - bc
      - command-not-found
      - curl
      - dnsutils
      - fd-find
      - firmware-iwlwifi
      - firmware-linux
      - fzf
      - git
      - htop
      - jq
      - man-db
      - mlocate
      - molly-guard # prevents accidental shutdown of server
      - net-tools
      - netcat
      - ntp
      - pv
      - ripgrep
      - screen
      - smartmontools
      - strace
      - sudo
      - unattended-upgrades
      - vim

- name: Update command-not-found
  become: yes
  command: update-command-not-found
  args:
    creates: "/var/lib/command-not-found/*"

- name: Copy ssh keys
  when: copy_ssh_keys
  no_log: yes
  copy:
    mode: 0600
    src: "{{ item }}"
    dest: /home/do/.ssh/
  loop:
    - /home/do/.ssh/id_rsa
    - /home/do/.ssh/id_rsa.pub

- name: Process dotfiles
  include: dotfiles.yaml

- name: Activate Magic SysRq
  become: yes
  copy:
    content: "# enable all sysrq commands\nkernel.sysrq = 1\n"
    dest: /etc/sysctl.d/99-sysrq.conf

- name: Increase inotify limits
  become: yes
  copy:
    content: "# Increase inotify limits\nfs.inotify.max_user_watches = 1048576\nfs.inotify.max_user_instances = 1024\n"
    dest: /etc/sysctl.d/99-inotify.conf

- name: Create bin directory
  file:
    path: ~/bin
    state: directory
